# Generated by Django 4.1.7 on 2023-03-30 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='status',
        ),
    ]
