# Generated by Django 4.1.7 on 2023-03-29 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
